### ISSUE TITLE
Add type hints and docstrings

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#100]
Per #84 and #86, add docstrings and type hints to all Python files to comply with pep8 standards and make the codebase more readable.

# Acceptance

* All Python modules, classes, and functions have at least one-line docstrings.
* All Python methods have their function calls fully type-hinted and are implemented free of misaligned type calls according to mypy linting.

**Comment by CarlinLiao** [comment]
I shouldn't be surprised but there's also a convention for Python docstrings, [PEP 257] and a linter to support those conventions called [pydocstyle.](http://www.pydocstyle.org/en/stable/) We should consider adding this as a development requirement.

**Comment by jimmymathews** [comment]
I added a disable flag to `.pylintrc` for function-level docstrings. I don't think it is helpful to add these uniformly across the whole codebase, it is likely to be a formality in the majority of cases (with uninformative 1-liner docstrings).

As part of #115 class and module level docstrings are all present. Could close with #115 merge.

**Comment by CarlinLiao** [comment]
[New tech for better documentation.](https://www.jwz.org/blog/2023/02/code-with-swearing-is-better-code/)
