### ISSUE TITLE
Fix linter complaints

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#105]
Per #84, here are the linter complaints that have yet to be addressed:

* pylint
   * prefer f-strings to `%` string formatting
   * use lazy `%` formatting in logging functions
   * `open` call doesn't specify encoding
   * constant name doesn't conform to UPPER CASE spelling style
   * redefine [variable name] from outer scope
   * complaint about the way an if statement is ordered
   * `!= None` -> `is not None`
   * consider iterating over a dict directly instead of calling keys()
   * unused variable
      * (in tuple returns where only some components are used)
      * (in a try-except)
      * (in a test)
      * (if it's the only line in a function)
   * consider using enumerate instead of range and len
   * consider iterating over a dict using items instead of over key lookups
   * variable name doesn't conform to snake_case
   * ~line too long in the case of a string that doesn't have an obvious breakpoint (e.g., URLs and regex, whereas SQL statements are easily breakable)~ let's leave them as-is
   * unused argument
   * anomalous backslash (on regex expressions)
   * hyphenated .py filenames instead of snake_case
   * imports not grouped (in the case of try/except imports not in the header of a file)
   * no exception type specified
   * dangerous default value ([], {}, etc.)
   * subprocess.run call doesn't explicitly set "check"
   * implictly defined variables in a class and for loop (e.g., check for one variable assures that another variable isn't unassigned)
   * super init not called
   * overriden child class function has more parameters than original
   * `assert condition == False` should be `is False` or `assert not` depending on if you're testing for exactly false or falsiness
   * unnecessary pass in abstract methods
   * using possibly unidentified loop variable
* pylance
   * ~function already defined (`get_phenotype_criteria` is defined thrice but is attached to a different flask endpoint each time)~
   * define new function instead of assigning a lambda a variable name
   * defining class attribute outside of init
   * [class instance] has no [attribute] (when creating the new property by assigning to it)
   * argument has incompatible type (when calling a builtin function that is correctly type hinted with a user-defined variable that isn't)
   * incompatible type when assigning to a dict
* spellcheck: [many variable names] is not a word (although interventional is definitely not a word)

# Acceptance

All issues on this list are fixed, or have an explanation added as to why we've chosen not to fix it.

**Comment by CarlinLiao** [comment]
Should I rename dashed python script names to underscores? @jimmymathews

**Comment by jimmymathews** [comment]
Yeah these can be converted to dashed CLI command names by pyproject.toml spec I think.

**Comment by CarlinLiao** [comment]
Some of these string formattings are really tricky to convert to f-strings --- you really took advantage of how python has multiple different ways to format strings.
```
('{0:0%sb}' % str(number_channels)).format(binary)
```

**Comment by jimmymathews** [comment]
That example should perhaps be regarded as not really an example of string formatting. It's more like data type conversion.

**Comment by CarlinLiao** [comment]
In the `HALOCellMetadataDesign` class, `get_combined_intensity` has an unused variable `elementary phenotype`. Is this intentional or indicative of a future feature? Otherwise it should be removed.

**Comment by jimmymathews** [comment]
I believe that you are referring to nearby method `add_combined_intensity_column`. And yes, that seems to be a mistake; that method is more like `add_all_combined_intensity_columns`.
The intensity-related functions were effectively deprecated at some point, due to unstable input data formats. There is a new issue now (#125) that should restore this functionality and this issue is meant to resolved by a rewrite of all related functions (`get_cominbed_intensity` and `add_combined_intensity_column` included).
