### ISSUE TITLE
Erroneous use of temporary/container db config

### ISSUE THREAD

**Issue by jimmymathews** [nadeemlab/SPT#114]
The file `.spt_db.config.container` is referenced by library code incorrectly.

Also, this file should belong to the build tree exclusively.

**Comment by CarlinLiao** [comment]
The first half of the issue is picked up by the linter, so it's rolled into #105.

**Comment by jimmymathews** [comment]
Not sure which commit exactly resolved this but it is not fixed (at least in #115)
