### ISSUE TITLE
Possibly unbound variables after for loop

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#117]
Per #115, in `workflow/phenotype_proximity/core.py`, there are possibly unbound variables `fov_index` and `table`. They're unbound because they're defined in the instantiation of a for loop, so if the thing being looped over is empty they're unbound. They're used outside of the for loop, so the only values they'd take on are as the last ones in the looped-over list.

"The fov indices are meant to be deprecated, but in some places they persistent formally (I think when there is just 1 fov index to loop over, so no error should occur)."

**Comment by jimmymathews** [comment]
Should be addressed by #115 .
