### ISSUE TITLE
New workflow steps, significant differences: phenotype fractions, proximity

### ISSUE THREAD

**Issue by jimmymathews** [nadeemlab/SPT#121]
Part of the SQL views for the backend database includes the "phenotype fractions" metrics, the fraction of cells of a given phenotype (or pre-defined "composite" phenotype) in a given sample. Also, after the proximity workflow, a bunch of `quantitative_feature_value` records are created, comprising many other sample-level features.

For this issue:
- Add an assessment step to the phenotype proximity workflow, and to the `spt db create-schema --refresh-views-only` function:
  - For each sample cohort pair (see table `sample_strata`) for a given study, and for each feature, compute a t-test for significant difference in mean between the feature values along the two cohorts.
  - Store the results as records in `two_cohort_feature_association_test`.
- Update the API handlers that provide fraction metrics and proximity metrics (already specified at the level of sample cohorts), to provide an additional column indicating which other cohorts have significantly different feature values (for a given p-value threshold, provided via the API call signature).

A few minor tasks need to be completed before the above can be attempted:
1. The phenotype fractions values need to be transcribed into the `feature_specifier/feature_specification/quantitative_feature_value` system, in order to be referenceable by feature specification identifier. Just like the proximity metrics. This should perhaps be done as a wrap-up task as part of `spt db create-schema --refresh-views-only`.
2. The `sample_strata` records need to be transcribed into `diagnostic_selection_criterion` in order to be referenced by the `two_cohort_feature_association_test` records. This is not a perfect fit and strains this portion of the data model, but it is functionally acceptable for now. This should perhaps be done at the same time that the `sample_strata` records are populated.

**Comment by jimmymathews** [comment]
Also deprecate: `PhenotypeProximityAnalysisIntegrator.do_outcome_tests`.

**Comment by danjafish** [comment]
https://github.com/nadeemlab/SPT/tree/issue121

**Comment by jimmymathews** [comment]
Let's reduce the scope of this issue by omitting the stats calculation for the phenotype proximity features.
I have a plan brewing to convert the proximity metrics calculation from a whole-study workflow to something that is computed for single samples and phenotype pairs on-the-fly as requested by the UI user.

**Comment by danjafish** [comment]
Hi @jimmymathews, there are a few questions that still need to be addressed:

1. Should we remove the t-test calculation for phenotype proximity altogether?
2. When inserting fraction values into the `quantitative_feature_value` table, what identifier should be used as the `subject`? Since the average percent doesn't correspond to any particular subject, I am unsure what to use.
3. I've noticed that running the phenotype proximity workflow multiple times introduces additional features. Is this a bug?
4. On a separate note, could you please direct me to the API step that returns information from the t-test?

**Comment by danjafish** [comment]
Furthermore, what should be the logic for calculating the t-test for different "measurements"? For instance, for different subjects in unrelated groups (e.g., healthy and sick patients). In general, I think, the t-test should not be calculated between such groups.

**Comment by jimmymathews** [comment]
1. Yes.
2. The fractions that are intended to get transcribed into the "feature values" tables (using `ADIFeaturesUploader`) appear in view: `fraction_generalized_cases`. These are at the specimen/sample resolution. So the feature "subject" is the specimen/sample identifier.
3. Definitely a bug!
4. The API endpoint that serves fractions summary currently is `/phenotype-summary/`, this is the one that needs to be changed to add statistical significance to its results.
