### ISSUE TITLE
New outputs, GNN

### ISSUE THREAD

**Issue by jimmymathews** [nadeemlab/SPT#122]
For this issue, make sure that the `spt cggnn` commands:
- Actually produce new feature values for samples, using the `feature_specifier/feature_specification/quantitative_feature_value` system.
- Assess the new features, adding `two_cohort_feature_association_test` records.

Also add an API endpoint that serves a table of the summary stats of the new features, just like the phenotype fractions table.

Based on the discussion in #85, I believe that the new features can just be: the number or fraction of cells of a given phenotype which belong to the top `k` highest-importance-ranked cells for some fixed `k` (e.g. `k=100`).

**Comment by jimmymathews** [comment]
@CarlinLiao

**Comment by CarlinLiao** [comment]
[cg-gnn#6,](https://github.com/CarlinLiao/cg-gnn/issues/6) and by extension `spt cggnn`, will produce the sample values as a DataFrame that will contain all the information necessary to comply with the `quantitative_feature_value` system.

**Comment by CarlinLiao** [comment]
[This already-implemented module in cg-gnn](https://github.com/CarlinLiao/cg-gnn/blob/main/cggnn/explain/specimen_importance.py) provides one importance score for every histological structure in a study (unless that histological structure was not included in any ROIs generated by the GNN pipeline, in which case it can be assumed that that structure's importance is 0) as a dictionary of `int` indexes to `float` importance scores. (It assumes that histological structure IDs are unique across an entire study, so it doesn't make a distinction between what specimen the structure came from, and just does a weighted average of all the scores for a single ID together.)

Using these functions, we can write a method to grab the top `k` highest ranked cells and do calculations for them. Would that be considered your scope or mine?

**Comment by jimmymathews** [comment]
Sorry I never answered this! It seems this issue is subsumed by new #171  .
