### ISSUE TITLE
Add squidpy features

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#176]
Per in person discussion, we'll be adding a new set of calculated features that are derived using the squidpy library:
* [`gr.nhood_enrichment`](https://squidpy.readthedocs.io/en/stable/api/squidpy.gr.nhood_enrichment.html#squidpy.gr.nhood_enrichment)
* [`gr.co_occurrence`](https://squidpy.readthedocs.io/en/stable/api/squidpy.gr.co_occurrence.html#squidpy.gr.co_occurrence)
* [`gr.ripley`](https://squidpy.readthedocs.io/en/stable/api/squidpy.gr.ripley.html#squidpy.gr.ripley)
* [`gr.spatial_autocorr`](https://squidpy.readthedocs.io/en/stable/api/squidpy.gr.spatial_autocorr.html#squidpy.gr.spatial_autocorr)

Features that require two clusters (e.g., co_occurrence) will be queried for and displayed separately from other metrics.

Execution process
1. Write standalone function that accepts a DataFrame of cell x and y positions (and cluster identifier in the case of co_occurence) and returns a vector of squidpy metrics
2. Integrate above function into `db` and `schema`
3. Make above available to the web API and add tab to SPT website

**Comment by CarlinLiao** [comment]
I suppose this is a duplicate of / clearer plan for #120.

**Comment by jimmymathews** [comment]
If you are working on this, let's work in branch `issue176`. I may be able to contribute as you are doing this.

**Comment by CarlinLiao** [comment]
I don't see a branch `issue176` in the remote.

**Comment by jimmymathews** [comment]
It doesn't exist yet!

**Comment by CarlinLiao** [comment]
How do you decide whether to wrap ondemand functions in a class or not?

For example, why is `ProximityProvider` a class instead of a suite of standalone functions that take a data object of cell locations and output proximities a la carte? Should our squidpy metrics follow this same pattern and instantiate an instance of the `SquidpyMetrics` class, or could it just exist as something that takes in cell locations and phenotypes and outputs a metric vector?

**Comment by jimmymathews** [comment]
There are two major reasons that I tend to consider as justification for promotion to a class:
1. There are many functions all supporting the functionality of one or a handful of entrypoint functions. Here most functions will be static or class methods. The idea is that future refactorers will be prevented from accidentally breaking up co-dependent functionality, and it is easy to bring all functionality to another context with one import (the class). It's a modularity pattern, separation (and isolation) of concerns.
2. There is state. When a bundle of co-supporting functions have 5, 10, 15 arguments that are repeated often, or even just one (structured) argument that is consistently repeated, the operation logic is obscured by argument passing which could be removed by setting to rest the arguments in (temporarily) persistent object state.

(2) is the main reason that `ProximityProvider` is a class. There are a lot of stateful references to the cached data which support each query. It is not reasonable to re-load these into memory on every request, the whole bundle takes about 5 minutes.

(Aside: I think `ProximityProvider` as it stands is suffering from too many responsibilities, it could be split at least into a loader and a query handler. If refactored very well, it would be reasonable to have a single isolated function which is the entrypoint into its functionality, which is perhaps closer to what you are envisioning as the ideal state.)

**Comment by jimmymathews** [comment]
As for the squidpy case, I think the initial design will be heavily constrained by performance considerations. It was non-trivial to design the `ProximityProvider` to be capable of handling an arbitrary cell-set-definition on demand for each query, making use of location data for this set (ultimately it leans on scikit tree data structures preloaded before query).

As we intend to rely on squidpy implementations, it seems we must do a cell-set-with-locations retrieval operation before each squidpy call. `ProximityProvider` and `CountsProvider` both have examples of a way to loading up the cell location and phenotype data from a prebuilt cache file. The code is a bit messy but I think the strategy can be copied to support squidpy metrics calculation as well.

**Comment by CarlinLiao** [comment]
Along those lines, what would our desired functionality be? I'm imagining something like
1. After choosing a study, the user navigates over to the squidpy tab on the SPT website.
2. On the squidpy tab, they're presented with pre-calculated metrics from squidpy's `spatial_autocorr` (as this is the only metric we identified that doesn't require a clustering specification, instead doing it itself using genes provided). (I assume we're only providing it with the simple phenotypes and not the complex phenotypes.)
3. Alongside `spatial_autocorr` results, the user is presented with an option reminiscent of proximities that allows them to choose how they want to cluster cells for the other squidpy metrics. This fires an API call off to the ondemand server, which takes the study and phentotypes to cluster on and does that calculation live if it can't find a cached result.

One thing to note is, if I'm interpreting this correctly, squidpy metrics are intended to be used per sample and not per study. So functionally it should return a vector of results per sample.

So functionally the plan of attack should be to
* Write a function that can calculate `spatial_autocorr` data artifacts for every study, a la `fractions_transcriber`.)
* Write a `ProximityProvider`-like class that will load cell location and phenotype data and then run the calculation that needs doing.

On the too many responsibilities point, if both `ProximityProvider` and `CountsProvider` already have the load-cell-location-and-phenotypes functionality, can't this just be shared across all three providers? Not just in terms of code but maybe it would save memory if each of the providers could ask a separate, fourth module for the loaded data since they all use the same data anyway. We could open a new issue for this.

**Comment by CarlinLiao** [comment]
Also is there any particular reason why the Providers (and the transcribers) use SQL queries instead of `FeatureMatrixExtractor`? That seems like it'd be a lot simpler.

**Comment by jimmymathews** [comment]
Your elaboration of (1), (2), and (3) is pretty much what I had in mind.

On the other hand, we could perhaps save ourselves a lot of time by substantially reusing the heatmap grid UI widget which already exists to support the cell counts functionality. (By reuse I mean use the exact same ones, not making copies in a new tab.)

This is because it already allows the user to
- create their own phenotypes, or select existing ones
- select 1 or 2 such phenotypes respectively (to select 1, select from the single column of tiles, to select 2, select a tile from the square grid)

We could then add just one more widget to that tab, for selection of the type of statistic (e.g. ripley, co-occurrence).
Then after just a few clicks a new column can be tacked on to the end of the existing per-sample table.

And yes, it would be good to have Proximity and Counts searching the same in-memory store to save memory. If I remember correctly this memory amount is not trivial! Currently they are not really using the in-memory cell data the same way, but possibly they could be rewritten to do so.

**Comment by CarlinLiao** [comment]
I'll look into the rewrite of the Providers.

I'm currently writing a `squidpy_transcriber` and trying to use `FeatureMatrixExtractor` as a drop-in replacement for SQL queries in the transcriber pattern, but I'm observing that it's not a drop-in replacement because the transcriber uses `DatabaseConnectionMaker` instead of `database_config_file` like `FeatureMatrixExtractor` does. How close are these two? Can we look into making the way functions connect to the database more consistent instead of alternating between DCM and config files depending on how long ago the function was written?

**Comment by jimmymathews** [comment]
Well as far as I remember the CountsProvider does not use SQL at all and does not reference the database at all. It does its work entirely from the pre-created cache, it is a mini-database of its own.

The ProximityProvider uses a few SQL queries because
(1) it caches its results in the "quantitative feature value" sector of the DB, and
(2) it uses a poor man's task queue created directly in the DB.
But none of these SQL queries overlap functionally with what `FeatureMatrixExtractor` provides, which is to read out a big bundle of data. Instead, ProximityProvider gets its *input* directly from the pre-created cache.

The moral is that all the SQL selects which involve cell-level data cannot be done live. And that is due to a special feature (large scale) of our problem domain (single cell studies).

The fractions transcriber does not need to use `FeatureMatrixExtractor`, because it starts from a couple of DB views just after they are refreshed. This transcriber's task is easy (thanks to the views). If we wanted to deprecate those views, we *would* need something like `FeatureMatrixExtractor` here.

**Comment by jimmymathews** [comment]
The difference between `DatabaseConnectionMaker` and `database_config_file` is no big deal. The former uses the latter. If the latter is not available, the former searches environment variables.
If `FeatureMatrixExtractor` relies on an older pattern, it's probably pretty trivial to align it with the pattern we're using now.

**Comment by jimmymathews** [comment]
As for different DB accessors, it is mainly about whether credentials are specified by a file or environment variables or direct arguments.
More and more of the code is to support containerized services, which generally prefer environment variables. Yet `FeatureMatrixExtractor` was created mostly for command-line custom workflows (cggnn) for which it was initially supposed that they would be run manually at the CLI. The SPT application services don't use `FeatureMatrixExtractor` currently.

**Comment by jimmymathews** [comment]
(which is why there was no pressure to change `database_config_file` => `DBCursor` or something else, in `FeatureMatrixExtractor`.)

**Comment by jimmymathews** [comment]
Again, to be clear: No SQL queries are used in the "Providers" to read cell data, the way that `FeatureMatrixExtractor` does. Instead, the Providers start from pre-pulled cache files.

**Comment by CarlinLiao** [comment]
Another question: should `squidpy_transcriber` (and transcribers in general) be written to be run for a single study or all studies? Functionally I assume we'd want to create squidpy features for all studies at once, but practically we may not want to rerun transcription for all studies whenever we add a new one. (The difference between the two implementations is trivial.)

**Comment by jimmymathews** [comment]
I would say everything should be study specific at the moment. We haven't yet attempted cross-study queries, though this is a major possibility opened up by having such a comprehensive single db!

**Comment by jimmymathews** [comment]
The transcriber language was used for when some values have already been computed, and they only need to be transcribed into the appropriate DB area (the "quantitative feature value" table and friends).

For the squidpy case, we have to do both computation and transcription, so `squidpy_transcriber` might not be the right term (unless you only mean the transcriber part).

**Comment by CarlinLiao** [comment]
I'll rename it to account for calculation and transcription. I don't see a need for them to be in separate files.

`FeatureMatrixExtractor` by default creates matrices for every study.

**Comment by jimmymathews** [comment]
Ah yes, I remember that one of the last changes made to that code was to expose `FeatureMatrixExtractor` functionality in a study-specific manner. You just have to supply `study` kwarg.

**Comment by CarlinLiao** [comment]
Speaking of, the way it's called in cggnn doesn't include it in the kwarg but as an indexer.

https://github.com/nadeemlab/SPT/blob/f724e7f4e15dff97774f53a7d7fcc7291d07d55f/spatialprofilingtoolbox/cggnn/scripts/run.py#L165-L168

**Comment by jimmymathews** [comment]
Hm yes that will do a large pull of all studies, then discard most of them I guess.

**Comment by CarlinLiao** [comment]
We probably don't want to do that.

Also, if I'm reading this correctly, `FeatureMatrixExtractor` creates three DataFrames per study, one with the actual features (centroids and phenotype information labeled as "F{x}"), one that translates feature column names "F{x}" to the names of the actual phenotypes, and one that identifies specimen cohorts. If I understand this correctly, why not simply rename the columns of the first DataFrame with the second?

**Comment by jimmymathews** [comment]
The trouble is that the phenotype names are uncontrolled strings, which are not very appropriate for column names. It can be done but we risk silent errors due to possible pandas-internal assumptions about column names, unless there is some kind of documented promise that "column names can be any string with up to 512 ascii characters" or similar. Pandas routinely makes guesses about data values and transforms them without warning, e.g. when making integers out of string columns if it thinks it found a pattern, or treatment of empty strings as nulls, and many other things.
This is a defensive implementation that is low-trust in pandas (in response to those experiences).
A non-defense implementation could be done, making use of pandas indexes etc. Feel free to implement this.

**Comment by CarlinLiao** [comment]
If we did want to share the use of the data in memory we'd have to have some kind of service that started with the server and, once called, just sits there with the data sitting in memory waiting for it to be used. An alternative is that, whenever any of the Providers that uses the data object is called, after returning (yielding, in REST parlance if I understand correctly) the first metric the service continues to calculate the other metrics before dumping the data from memory. That or calling one Provider calls all three Providers and they're returned together.

**Comment by CarlinLiao** [comment]
Organizational thought: we may want to consider additional subdirectory organization in db, ondemand, and workflow. There's getting to be a lot of modules in there.

**Comment by jimmymathews** [comment]
Yeah I agree. There has not really been a review cycle over the ondemand functionality, most of what is there is the first implementation.

**Comment by CarlinLiao** [comment]
I've been refactoring the providers to share a base Provider class, but you've stumped me with use of the pipe operator, which I'm not sure of the use of (bitwise OR?) or order of operations (does it evaluate before or after `==`?). See here:

https://github.com/nadeemlab/SPT/blob/f724e7f4e15dff97774f53a7d7fcc7291d07d55f/spatialprofilingtoolbox/ondemand/counts_provider.py#L82-L102

I've refactored `data_array` to be a DataFrame instead of an int array to be consistent with `ProximityProvider`, with the column `'entry'` being consistent with the prior implementation of `data_array`. This has the benefit of allowing us to use vector operations instead of for loops. How would we translate the above for loops into pandas vector operations?

**Comment by jimmymathews** [comment]
I did try to use DataFrames to replace the counts provider's list of ints, but the performance hit was unbearable (like 100 times worse or something like that). By encoding the binary feature vector as the bits of a 64 bit integer, assessing 1 cell for consistency with a given signature becomes a single bitwise operation. I think this is the reason that this is able to work in realtime across 2 million cells. (Note that if pandas alwasy does some smart parallelization thing behind the scenes for vector operations, we could *still* use the ints setup with a single Series (as opposed to dataframe) and get the benefit of vectorization, where the function applied to each entry is the bitwise operation.)
I tried various indexes to reproduce this functionality in a DataFrames version, but I did not succeed. You may have more success, let's see if you can get the performance to be comparable.

**Comment by CarlinLiao** [comment]
I can't because I don't understand what it's doing. In lieu of that, I'll have the unwrap the DataFrame into a interable of ints so the original functionality is preserved. Here's hoping that packing the 64 bit ints into a DataFrame doesn't cause some weird interpolation in the process.

**Comment by CarlinLiao** [comment]
A stray thought that I'm not going to implement for fear of further introducing more potential bugginess to `CountsProvider`: the channel names parameter would be better served as a set instead of a list, and the output `[count, len(data_array)]` and such would be better served as a tuple instead of a mutable list (barring some change to the list that I'm not aware of).

**Comment by jimmymathews** [comment]
(First of all, the functions `count_structures_of_exact_signature` and `count_structures_of_partial_signature` seem to be present for completeness, from a prior time when more functionality was offered by this module than we are currently using. Only `count_structures_of_partial_signed_signature` is used, as grep will show. So if you'd like you can delete the other two functions.)
The line to understand is here:

https://github.com/nadeemlab/SPT/blob/f724e7f4e15dff97774f53a7d7fcc7291d07d55f/spatialprofilingtoolbox/ondemand/counts_provider.py#L98-L99

`entry`, `positives_signature`, and `negatives_signature` are ints whose bit sequence corresponds to the channel list. `entry` is the cell's actual expression vector, and `positives_signature` and `negatives_signature` are also in such binary format and together represent the signature or cell type definition. (As in e.g. `CD4+ CD56- cell`, a cell which is positive for CD4 but negative for CD56.)

`entry | positives_signature == entry` is true if and only if the cell is positive for each channel requested to be positive.

`~entry | negatives_signature == ~entry` is true if and only if the cell is negative for each channel requested to be negative.

If both conditions are true, the cell conforms to the cell type definition queried for.

**Comment by jimmymathews** [comment]
And yes, the channel names is intended to represent a set in reality, so a set data structure would be in better alignment with the intent.
Also the mutable list return value is a mistake, you are right.

**Comment by jimmymathews** [comment]
The whole business of "target index lookup" and symbols and everything is overcomplicated. I believe I did this to make sure that both the DB integer global identifiers and a study-specific integer enumeration are available to this function, for possible debugging purposes.

**Comment by jimmymathews** [comment]
Overall I would say you can be pretty adventurous with breaking changes especially if they improve readability and deprecate hard-to-understand code. We can be fairly confident that nothing important is broken before merge or release because of the test suite.

**Comment by CarlinLiao** [comment]
(Not if the tests won't work on my machine lol.)

The new `FeatureMatrixExtractor` asks for a `DBCursor`, which makes sense. However, `db.squidpy_metrics`, following in the pattern of `db.fractions_transcriber` and `db.importance_score_transcriber`, expects a `DatabaseConnectionMaker`, which, being a parent class of `DBCursor`, can't create a cursor. If I want to use `FeatureMatrixExtractor` in `squidpy_metrics`, how should I resolve this?

**Comment by jimmymathews** [comment]
I think `FeatureMatrixExtractor` asks for a `psycopg2.extensions.cursor`. So you could start from a `DatabaseConnectionMaker` or a `DBCursor`:
```py
with database_connection_maker.get_connection().cursor() as cursor:
    extractor = FeatureMatrixExtractor(cursor=cursor)
    ...

with DBCursor() as cursor:
    extractor = FeatureMatrixExtractor(cursor=cursor)
    ...
```

**Comment by CarlinLiao** [comment]
Oh I see. Is the word "cursor" overloaded syntactically?

**Comment by jimmymathews** [comment]
Not exactly, in both cases `cursor` is a `psycopg2.extensions.cursor`.
The context manager `DBCursor` returns a `psycopg2.extensions.cursor` as the context object.

**Comment by jimmymathews** [comment]
For the benefit of lookup, that monster bundle that we keep trying to Type has the following form:

```json
{
  "Melanoma intralesional IL2": {
    "feature matrices": {
      "lesion 0_1": {
        "dataframe": null,
        "filename": "0.0.tsv",
        "continuous dataframe": null
      },
      "lesion 6_1": {
        "dataframe": null,
        "filename": "0.1.tsv",
        "continuous dataframe": null
      }
    },
    "channel symbols by column name": {
      "F0": "B2M",
      "F1": "B7H3",
      "F2": "CD68",
      "F3": "CD8",
      "F4": "DAPI",
      "F5": "FOXP3",
      "F6": "IDO1",
      "F7": "KI67",
      "F8": "LAG3",
      "F9": "MHCI",
      "F10": "MHCII",
      "F11": "MRC1",
      "F12": "CD14",
      "F13": "PD1",
      "F14": "PDL1",
      "F15": "S100B",
      "F16": "SOX10",
      "F17": "TGM2",
      "F18": "TIM3",
      "F19": "CD163",
      "F20": "CD20",
      "F21": "CD25",
      "F22": "CD27",
      "F23": "CD3",
      "F24": "CD4",
      "F25": "CD56"
    },
    "sample cohorts": {
      "assignments": null,
      "strata": null
    }
  }
}
```
All the "nulls" above are dataframes.

So it is not `dict[str, dict[str, DataFrame | str]]`.

Due to the nesting there isn't much benefit to be gleaned by attempting to retroactively describe the type for the above. Instead we should do proper typing (make the above a composite of 3 things, each their own first class type, etc.), or else just keep it as is for the time being.

**Comment by jimmymathews** [comment]
The mypy linter was making me OCD so I just added this megatype for the time being and a ton of `cast`s:
```py
BundlePart = dict[str, DataFrame | str | dict[str, DataFrame | str ]]
Bundle = dict[str, dict[str, BundlePart]]
```
