### ISSUE TITLE
Replace filesystem intermediate cache files

### ISSUE THREAD

**Issue by jimmymathews** [nadeemlab/SPT#221]
During work on spt-dashboard [#63](https://github.com/nadeemlab/spt-dashboard/pull/63) in which 3 services with different functionality all need read-access to the same store of pre-computed cache files (compared with the current setup with 1 mega service), it became clear that using such a file-based mechanism poses some problems.

The place the files are stored is a persistent volume, but there is no clear relationship between the contents of this volume as seen by different containers at a given time. There is some sort of sync issue, sometimes seemingly taking hours to reach consistency if at all.

We considered an S3-based replacement for the mounted volume. Also @apetrov-msk suggested an in-memory database service to replace this functionality. All that would be needed is a simple key-value store, and indeed even such a key-value store would be an improvement over the current situation in which filenames need to be separately indexed (associated with sample names, etc.).

After looking at some of the options (Redis, memcached, even gdbm), I think the best thing might be a big new table in the postgresql database. Then no new services are needed. The table could be called `binary_cache`:

| study | specimen | blob_type | blob_contents |
|-------|-------|-------|------|
| VARCHAR(512) | VARCHAR(512) | VARCHAR(512) | [bytea](https://www.postgresql.org/docs/current/datatype-binary.html#DATATYPE-BINARY-BYTEA-ESCAPE-FORMAT) |

| study | specimen | blob_type | blob_contents |
|-------|-------|-------|------|
| Breast cancer IMC | sample1 | feature matrix | ... |
| Breast cancer IMC | sample1 | positions | ... |
| ... | ... | ... | ... | 

The total additional storage size needed is about 500mb for our current data load.

For this issue, let's add this table spec to [performance_tweaks.sql](https://github.com/nadeemlab/SPT/blob/main/spatialprofilingtoolbox/db/data_model/performance_tweaks.sql), and update the following to stop using those cache files and instead use the new table:

- [structure_centroids_puller.py](https://github.com/nadeemlab/SPT/blob/main/spatialprofilingtoolbox/workflow/common/structure_centroids_puller.py)
- [structure_centroids.py](https://github.com/nadeemlab/SPT/blob/main/spatialprofilingtoolbox/workflow/common/structure_centroids.py)
- [sparse_matrix_puller.py](https://github.com/nadeemlab/SPT/blob/main/spatialprofilingtoolbox/workflow/common/sparse_matrix_puller.py)
- [OnDemandProvider](https://github.com/nadeemlab/SPT/blob/main/spatialprofilingtoolbox/ondemand/providers/provider.py)

This work will need to be completed before spt-dashboard [#63](https://github.com/nadeemlab/spt-dashboard/pull/63) can be completed, because the latter is not stable using the mounted-volume system.

\* I think the reason this option was not considered long ago is that I forgot that sql databases support large binary blobs as values.

**Comment by wooferclaw** [comment]
#295
