### ISSUE TITLE
Bring data transformation features from `cg-gnn` to SPT

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#239]
Per in-person discussion, we should move cell graph creation from the `cg-gnn` pip package into SPT.

This was motivated by two things:
* Clarifying the separation of concerns between SPT and `cg-gnn`
* Holding all Nadeem-lab developed code in SPT while preserving externally-derived code in `cg-gnn`

I'd like to take the opportunity to have a broader discussion about what features should be in SPT versus `cg-gnn`. My interpretation is that SPT should house everything related to
* data ingestion (processing new studies into SPT-compatible format, uploading derived features into the database)
* data warehousing (uploading, storing, and providing data from the SPT study database)
* data transformation (processing data from the database to arrive at desired output, e.g., proximity metrics and cell graphs)

`cg-gnn` should only handle deep learning model training. Arguably this is also a really complex version of data transformation, but I think the complexity of this process is sufficiently abstract that it should live in its own repository. And for another reason, more on this later.

Broadly, `cg-gnn` can be described as doing three things, with subdivisions:
1. Create cell graphs from SPT data extracts and divide them by specimen into training, validation, and test sets
2. Train and infer a deep `CellGraphModel` on the created cell graphs
   a. Load cell graphs into memory to prepare to provide it to the model
   b. Train the model
   c. Infer using the model
4. Explain the model's behavior
   a. Calculate the importance of each cell as found by the model
   b. Create interactive HTML topographic graphs of each cell graph
   c. Calculate separability scores metrics of the classes the model is trained on

In my opinion, 1 and 3 are clearly what should be SPT's concern, while 2 should remain in `cg-gnn`. But this runs into the code provenance concern. 1, 2a, and 3b were written wholly by me while 2b, 2c, 3b, and 3c are derived from `histocartography` and `hact-net`. So depending on if we prioritize the separation of concerns or the code provenance, a different subset of features will be moved into SPT.

We also discussed a third alternative priority. As @sanadeem has suggested, we could organize the framework such that the exact choice of deep learning model is drop-in replaceable. We can make it so that `cg-gnn` is replaceable with any other deep learning model framework that can use the same cell graph data format.

With this in mind, `cg-gnn` features 2b, 2c, and 4a are the only ones that involve using the deep learning model; all others only require either the data extracts or the cell graphs with importance scores calculated. If we move all other current `cg-gnn` features into SPT, it should give us a good balance of prioritizing separation of concerns and preserving code provenance while also enabling outside researchers to develop SPT-compatible deep learning models as long as they fit the pattern of accepting SPT-formatted cell graphs and returning cell-level importance scores.

**Comment by CarlinLiao** [comment]
Also, regardless of what we decide to do, creating cell graphs is moving from `cg-gnn` to SPT. We discussed parallelizing them in either Nextflow or Python native. I'll do that, but only after merging a PR that ports graph creating as-is. (HTML graph interactive creation is also parallelizable, if that's something we also choose to move.)

**Comment by sanadeem** [comment]
The third alternative with 2b, 2c, and 3a left in cg-gnn and the rest moved to SPT. Parallelizing both creation and interactive visualization will help.

**Comment by jimmymathews** [comment]
It seems that code provenance with respect to the steps you enumerated is not a significant consideration, given that histocartography and hactnet do not seem to be actually doing any of the model training or inference. This judgement could be wrong, as I'm not very familiar with `cg-gnn`'s source.
Isn't pytorch doing 99.9%, the heavy lifting? Can you explain an example of something in histocartography/hactnet that is (i) non-trival (the code in the repository is non-trivial), and (ii) actually used by us?

**Comment by CarlinLiao** [comment]
Regarding provenance,
* 2b, 2c, 3a, and 3c are directly from `hact-net` or `patho-quant-explainer` with only minor modifications.
* 1 and 2a are written to either take new inputs and output structures (cell graphs and DataLoaders, respectively) that are compatible with the minimally modified modules, but the actual implementations are original, if I recall correctly.
* 3b is, if I recall correctly, wholly original.

Following in-person discussion, we've agreed on leaving 2b, 2c, 3a, and 3c in `cg-gnn` and moving the rest to SPT. The first three is for reasons already delineated above, while 3c, separability scores, is newly added to the "leave in `cg-gnn`" set for two reasons
* code provenance
* in practice, we've never actually used the outputs it creates, and we only want to have functionality we plan to use in SPT

**Comment by jimmymathews** [comment]
(Auto-closed incorrectly.)

**Comment by jimmymathews** [comment]
To completely close out this issue, we discussed a few more items:

1. Remove `cg-gnn` as a dependency from the list in `pyproject.toml`.
2. Deprecate `spt cggnn run` and replace it with an equivalent `cg-gnn`-provided entrypoint. (And update `cg-gnn` accordingly, and any tests or similar that might depend on the former entrypoint syntax).
3. Modify `cggnn.nf` Nextflow definition for parallelization of the graph generation and graph plot generation (altering the process topology so that NF will be able to parallelize at runtime).

**Comment by CarlinLiao** [comment]
Something I've noticed that I should probably change for consistency's sake: for CLI scripts, my scripts use underscores to separate words while SPT's `add_argument` uses dashes. When updating some of the cggnn scripts to use `add_argument`, now some args for the same command use dashes while others use underscores.

**Comment by CarlinLiao** [comment]
Parallelized graph generation is done. Should I open a PR or hold off until plotting parallelization is done?

Some other things I'd like to do:
* Change all underscored CLI args to dashed.
* Refactor/streamline ROI creation to these options that are passed via a single overloaded arg. (This isn't fully thought out, to be honest, but I do think I can do ROI creation in a more intuitive way than it's currently implemented.)
   * Target cell count per ROI
   * Fixed ROI size
   * Size all ROIs according to the smallest specimen
   * 1 ROI per specimen
* Refactor `spt workflow config` so fewer parameters are passed via the CLI. My thought is that it could have as little as two args: a `database-config-file` and all workflow-specific parameters going in a `workflow-config-file`.

**Comment by CarlinLiao** [comment]
If I understood our in-person discussion correctly, completing the replacement of the `cggnn` run workflow with a parallelized implementation of cell graph generation was definitely enough for a PR, and possibly enough to close this issue since we deemed parallelized graph plotting not critical path?
