### ISSUE TITLE
Refactor `workflow` module to better match current SPT standards

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#247]
Per in-person discussion, `workflow` is a legacy submodule that could be worth revisiting and refactoring into our current conception of what SPT should be. I would describe a few of the suggestions I've floated as follows, in increasing order of complexity

* Refactor `spt workflow configure` to coalesce arguments not applicable to all workflows into a generic configuration file/YAML, to be read by python's `ConfigParser` with sections titled according to the workflow being run.
* Reorganize so that each workflow has its own `.nf` file, and potentially its own logic, in its own directory, to minimize the use of files from `assets/` or `common` to those that are truly common to multiple workflows.
* Carve `workflows` out into separate repo as a sort of or a literal plugin system, leaving only a few simple interface files in this repo/the spatialprofilingtoolbox pip package that SPT workflow plugins would import and build off of, to ensure compatibility with the SPT ecosystem.

**Comment by jimmymathews** [comment]
The first 2 items are fine if you'd like to work on them. This shouldn't take long.
The third item would constitute a major new feature and would require detailed planning.

**Comment by jimmymathews** [comment]
Your item 1 has been spun of as #278 , and item 2 is low priority (almost already how things are). Item 3 as I said would require an extensive plan, and it's not certain that it would be desired.

Note that `workflow` is not a "legacy" module as you say, it supports a core function (tabluar import), and could support more in the future, without any particular reason that it might benefit from a plugin system like the one being developed for graph processing.
