### ISSUE TITLE
Add tmi2022 GNN model

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#268]
[A recently released paper](https://doi.org/10.1109/TMI.2022.3176598) includes [a new GNN-Transformer architecture](https://github.com/vkola-lab/tmi2022) that may work better than the CG-GNN currently included in our dataset.

**Comment by sanadeem** [comment]
It should be the domain of CG-GNN. Variants such as transformers or the more recent cooperative message passing modules (https://arxiv.org/abs/2310.01267) that sit on top of the vanilla GNN should be agnostic to the data type.

**Comment by CarlinLiao** [comment]
Sorry, I meant SPT (although you could say that since SPT has subsumed CG-GNN it's all the same). I feel like it could set a bad precedent if it's the responsibility of SPT to form its outputs to match any odd cell graph model that wants to read from it, as opposed to having the cell graph model write its own DataLoader to parse SPT output.

**Comment by CarlinLiao** [comment]
I've developed a plugin that trains a tmi2022 model to create class activation maps / importance scores, so now it's left to integrate it into SPT. That will involve creating
1. a workflow that runs tmi2022, and a test to go along with it 
   * #289 is optional but very helpful for this
2. a new apiserver endpoint that returns importance scores created by tmi2022 (to complement the one from cg-gnn)

There are also some elements tracked outside of this repo, like
* new UI elements to go along with the new server endpoint
* a heat map of important cells as they relate to different phenotypes

**Comment by CarlinLiao** [comment]
I just remembered that tmi2022 requires a GPU to run. For this reason, I won't be adding a test for it.

**Comment by CarlinLiao** [comment]
A refinement of the goals listed above:
- Generalize `cg-gnn` workflow to support any canonical SPT graph plugin (i.e., spt-graph-transformer)
- Add richer identification information when uploading importance scores, including plugin used, version, and date time of run 
- Allow for fetching importance scores based on permutations of the above identifiers in the API
And of course modifying current tests to support above refactors and adding new tests where possible
