### ISSUE TITLE
Abstract out graph deep learning functionality to an external plugin system

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#272]
This would be implemented as follows
1. The `cggnn` submodule would be renamed to `graphs` to reflect the change in its responsibilities and disambiguate from the `cg-gnn` model. (This would also future-proof against a potential expansion to creating tissue/region graphs in addition to cell graphs that I think we'd want to do, but that's far outside the scope of this issue.)
2. This repository, SPT, would reduce graph functionality in the `graphs` submodule to the following:
   * **Output graphs**: Given a configuration with controlled fields like `graph_specs.yml` (i.e., an API call), output a data artifact with consistent structure to file that contains cell graphs constructed by SPT.
   * **Upload transformations**: Upload consistent output (presumed to be transformed versions of the output graphs, e.g., by a deep learning model), which includes importance scores per histological structure, to the database.
   * Other functions that can utilize the consistent input and output to do simple stuff with, like graph plotting.
3. Graph deep learning functionality would be abstracted and moved to an external plugin system.
   * Each plugin would have
      * A filled-out but study-agnostic version of `graph_specs.yml`, so it can be applied to any study uploaded by SPT.
      * A Docker container that would set up their environment to run their model, run their model on the data artifact, and output results in the format that SPT expects so they can be uploaded to SPT (importance scores to start with, but potentially more stuff like model checkpoints later down the line).
   * These Docker containers would be derived from a template GitHub repo that will be created to close this issue.
4. SPT `workflow` would be modified to get pinned versions of each plugin's Docker container to run the deep learning workflow(s).
   * (A later update will add functionality to `db` that triggers deep learning runs on upload of new studies in a similar fashion.)

Addition of new graph deep learning plugins to SPT would be done in three steps:
1. **Exploratory stage**: a user would evaluate if their deep learning model is good or not by manually using the output and upload functions described in the prior section and examining their results locally or in an SPT instance after upload.
2. **Proposal stage**: If a user determines that their graph model is a good candidate for inclusion into SPT as a default graph deep learning plugin that should be run on every new study imported into SPT, they would containerize their model according to the Docker template defined for the external plugin system, upload it to a GitHub repo or equivalent, and open an issue or pull request for SPT to include their plugin.
3. **Inclusion stage**: The SPT maintainers would quality check the proposed plugin and, if found to be worth including, upload the container to the SPT Docker page and modify SPT code to pull down and use that Docker image by default in SPT.

Implementation plan.
1. (Optional, but complementary.) Implement #271. Since we're abstracting out GNNs, this would allow us to reduce the number of dependencies that need to be installed to run SPT.
   * We could even go further and remove the pytorch dependency and just output graphs as numpy arrays since any graph deep learning would just be done in a separate Docker image.
2. #275
3. #277
4. #278, which closes #247 in part.
5. [Create the Docker plugin template repo and pattern and conform the `cg-gnn` model to it.](https://github.com/nadeemlab/spt-plugin/issues/2) This would also exemplify the pattern of proposal and inclusion into SPT.
   * Once this step is complete and tested, this issue would be closed.
6. Other features facilitated by this refactor:
   a. Apply the new plugin process to close #268
   b. This should give us a better idea of how to close the rest of #247 and if we want to reorganize workflow into the plugin system as well
   c. Add triggers to `db` to run the default GNN plugins on each new study when they're uploaded, if [spt-plugin#2](https://github.com/nadeemlab/spt-plugin/issues/2) is implemented in a compatible way

This functionality would be implemented in lieu of #269 and #270.

**Comment by jimmymathews** [comment]
This outline matches my understanding of our preliminary plans. I initialized a plugin template repository and first example repository.

**Comment by CarlinLiao** [comment]
For `cg-gnn`, I think it'd serve to move [the existing repo](https://github.com/CarlinLiao/cg-gnn) into nadeemlab.

**Comment by jimmymathews** [comment]
The problem with moving the existing former repository (rather than starting from a fresh fork the template repo) is that it reduces the utility of this repository to illustrate the recommended plugin development process. I would want us to follow the process that we will recommend to others for new plugins, including forking `spt-plugin` so that pulling general-purpose updates is standardized. It could be confusing for others to be asked to do something different from what we do in our 1 example already at the first step.

**Comment by CarlinLiao** [comment]
That's a good point.

In the target use case, a 3rd party model developer that wants to add their model to SPT. To that end, they package their model (that presumably exists independently in its own repo) in the form of a Docker plugin that is forked from or otherwise conforms to the `spt-plugin` template.

The plugin version of the model therefore draws from two sources: the `spt-plugin` template and the original 3rd party model repository and is arguably a fork of both, although GitHub doesn't support explicit multi-forking. Instead, I would imagine the plugin version of the model as living in the model's original repo as an `spt` branch, much like how open source packages often have a `release` branch that they update from main when they're ready to release a new version.

Alternatively we could encourage third party developers to write their code into a branch of `spt-plugin` so we could use GitHub's PR system to evaluate and approve future plugins. Or both! Plugin source in their original repo and a version that refers to their plugin's published Docker repo in `spt-plugin`.

Once we accept a 3rd party submitted plugin as an SPT default, it becomes something that we maintain, with provenance that allows us to pull in updates from 3rd party's source code. I think that means forking the 3rd party model from their source into SPT aka nadeemlab, instead of creating a new repo for it.

(In our actual use case, it's us the SPT team trying to use 3rd party models with SPT, so we're the ones forking the 3rd party repository and coercing it into the `spt-plugin` template. That fork might also live in my user account, with me and my fork acting as the pseudo-3rd-party that would then get forked again by nadeemlab when it's ready to be featured as an SPT default.)

**Comment by CarlinLiao** [comment]
Two thoughts that've occurred to me
* If we Dockerize deep learning training, we can't run them on the HPC. We can probably find workarounds for this, such as having the Docker container simply install an environment and run a script that are defined outside of the Dockerfile so we can run a very similar process without Docker available.
* It'll be very hard for a  since part of the process is manually identifying specimen cohorts that're good candidates for classification, as is the purpose of the `spt cggnn explore-classes` feature.

**Comment by jimmymathews** [comment]
Actually dockerization is supported on the HPC, via singularity. Singularity can create SIF singularity images from Docker images which Nextflow can easily use for specific processes, exactly as we plan. And singularity images can be executed with user-level permissions.

**Comment by jimmymathews** [comment]
Regarding your elaboration/speculation about the plugin repos:

I don't think it is correct that any plugin developers (whether us or external) will regard their plugin as having multiple inheritance in source code. As in other areas of software design ([example](https://en.wikipedia.org/wiki/Composition_over_inheritance)), multiple inheritance is probably not the answer. Instead, the ancestor is simply the plugin template. I don't think an external developer working on Software X that could be useful in SPT metrics would decide to create a descendant project of Software X specifically for SPT. Rather, they would just *use* Software X in the plugin code, as a normal software dependency.

**Comment by jimmymathews** [comment]
I also think we should not entertain the use of branches for plugin management. For an external contribution to a GitHub repository, as I understand it the normal process is a [PR from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork). That way no special privileges are needed to submit suggested additions. Due to the repo layout, the content of the PR to SPT repository could be especially simple: an alteration to the list of available dockerhub repositories to include the appropriate "dockerorgname/repositoryname:tag".

And I'm not sure we want to plan to absorb such plugins under our development responsibility. I think rather they are just open-source projects of their own that we or other could contribute to.

**Comment by CarlinLiao** [comment]
Following closure of #275 and merger of #276, the rest of the implementation plan will be completed in one shot for this issue. This will include
1. Renaming `spt cggnn` to `spt graphs`
2. Refactoring the graph generation command to take a configuration file instead of input arguments
3. [Establishing the spt-plugin template and conforming spt-cg-gnn to it](https://github.com/nadeemlab/spt-plugin/issues/2)
4. Refactoring `spt workflow configure` to conform to the new input signatures of 2 and 3.
   * This is sort of #278 but I'm concerned about extending changes to impact the other, crucial workflows. Maybe we handle that separately and here only do the minimum edits necessary to ensure that the cggnn workflow continues to work.
