### ISSUE TITLE
Would adding ` --no-cache-dir` to pip install commands slim down Docker image sizes?

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#274]
By default, pip caches downloads when installing a new package. That's useful typically but since our Dockerfiles are often tossed, the cached packages end up bloating the size of our images without ever getting used since if we want to renew our Docker image it discards the image and redownloads the wheels, if I understand this correctly. Would changing commands to, say,

```
RUN python -m pip install --no-cache-dir toml
```

reduce our memory footprints in a worthwhile way?

**Comment by jimmymathews** [comment]
Yes, I think your understanding is correct. It would save space to have pip install directly without first saving package files, or at least to delete them after they are installed. Similarly apt (for debian-derived images) by default caches system packages, which could also be deleted.

**Comment by jimmymathews** [comment]
I don't know if `--no-cache-dir` is exactly the right flag, because there are other possible readings of this flag (e.g. "don't install this package from cache, instead fetch it from remote").

**Comment by jimmymathews** [comment]
Also, even if we can come up with the correct command to install packages without caching them, pip's cache will likely contain things we didn't put there ourselves. Maybe it is better to clear the pip cache in one fell swoop at the end of the docker image's build. And the apt cache for that matter.

**Comment by CarlinLiao** [comment]
[Discussion about pip caching in the context of Docker.](https://stackoverflow.com/a/57490475/13216519) It's the right flag but [`ENV PIP_NO_CACHE_DIR=1`](https://stackoverflow.com/a/60270281/2248627) may be even better

**Comment by jimmymathews** [comment]
The problem with the option you've outlined is that it does nothing to the packages cached prior to any of our own pip runs. Instead of altering the normal pip installation procedure (spreading out and requiring non-standard behavior in a large number of places), a single cache removal step would accomplish the same result.

**Comment by CarlinLiao** [comment]
We could do both. This allows the memory footprint to stay as small as possible instead of growing as we make pip installs and then shrinking when we clear them all. (I would also imagine that the maintainers of the base images we use also implement no caching as a best practice.)

**Comment by jimmymathews** [comment]
Actually yes you are right, it seems that intermediate layers are still present (still downloaded when final image is downloaded?) even if their file contents are reduced in later layers. So there may be no way to act on this issue without the `--no-cache-dir` option on every pip call.

**Comment by CarlinLiao** [comment]
Setting [`ENV PIP_NO_CACHE_DIR=1`](https://stackoverflow.com/a/60270281/2248627) before doing any pip installs has the same functionality, as I understand it.
