### ISSUE TITLE
Dockerization of the `cg-gnn` model

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#275]
Pursuant to step 2 of #272's implementation plan, we should convert `cggnn` to use a Dockerized version of the `cg-gnn` model. Steps as follows:
1. Refactor the `cggnn` submodule to provide graphs and intake deep learning models using a model-agnostic I/O API (already done)
2. Excise and Dockerize the `cg-gnn` model from the SPT repo (undoing #257) and refactor it to use the new `cggnn` I/O API
3. Modify existing tests for `cggnn` and `workflow` to pass using the Docker container

Dockerizing `cg-gnn` will pave the way for implementing the plugin process described in #272 and have an immediate benefit of allowing us to remove torch and DGL from our SPT development Docker image, speeding up test suite runs dramatically.

**Comment by jimmymathews** [comment]
This is part of #272, as you've said.

**Comment by CarlinLiao** [comment]
Per our in-person discussion, we established that closure of this issue will represent a meaningful improvement to SPT in a development context because it will separate the cg-gnn model environment into a Docker container separate from the general SPT Docker container, reducing test time and slimming down the footprint of the general container.

**Comment by jimmymathews** [comment]
I am getting a failure of the standalone test, due to the actual checking of important cells:

```txt
24% of the most important histological structures match the reference, which is less than 50%
```

Is this expected? Should we update the reference?

**Comment by jimmymathews** [comment]
As far as I can tell this is not an indication of a major error anywhere, just reproducibility subtleties.
I rebuilt all images from scratch based on this branch and all other test pass, I think this is ready to merge.
