### ISSUE TITLE
Rename `cg-gnn` submodule to `graphs`

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#277]
Per #272, the `cggnn` submodule should be renamed to `graphs` to reflect the change in its responsibilities and disambiguate from the [cg-gnn model.](https://github.com/nadeemlab/cggnn)

This would also future-proof against a potential expansion to creating tissue/region graphs in addition to cell graphs that I think we'd want to do, but that's outside the scope of this issue.

**Comment by jimmymathews** [comment]
I don't think you need a separate issue for this. This is clearly "per #272". Many of the other recently created issues are also part of a single work item. Let's consolidate them into one place.

**Comment by CarlinLiao** [comment]
I'd like to create, test, and merge these as individual PRs instead of one big PR. Would you recommend doing it all in one go?

**Comment by jimmymathews** [comment]
Yes. They need to exhibit cohesion in order to be evaluated.

**Comment by CarlinLiao** [comment]
Rolled back into #272.
