### ISSUE TITLE
Refactor `spt workflow configure` to accept a generic configuration file instead of CLI arguments

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#278]
As suggested by #247 and necessitated by #272, allowing the user to swap graph processing plugins that likely have their own set of input configurations. (There was also discussion of removing configurability of the models altogether, but that would also be in line with this issue as the current options exposed for the `cggnn` workflow would need to be removed in that case.

The configuration YAML could look something like this, with a generic [settings] section that applies to all workflows and sections for specific workflows or graph models.

```
[settings]
db_config_file = ...
executor = ...
workflow = ...

[db_visitor]
file_manifest_path = ...

[graphs/cggnn]
strata = ...

[graphs/gnn-transformer]
depth = ...
```

The settings could but wouldn't need to be saved to the same config file, as the logic would only use the relevant section for the task at hand, and they're all named distinctly.

**Comment by jimmymathews** [comment]
This feature is valuable, but let's not confound it with the declarative configuration that was planned for the graph processing plugins. That (probably substantially slimmed down) configuration is perhaps better considered as supporting a single function call. Plugin developers should probably not need to be aware of `spt workflow ...`, with its other more low-level options.
