### ISSUE TITLE
Add a spatial-community-detection workflow

### ISSUE THREAD

**Issue by jimmymathews** [nadeemlab/SPT#42]
Use something like `networkx` (as in #41) to create a graphical representation of cell arrangement.
Then use standard graph-based community detection algorithms to find proximity communities.
Assess the communities somehow. For example, calculate each channel's intensity along cells in a given community, and compute community-size-weighted correlation for each channel pair. Then this correlation value (defined per slide or sample) can be used as an outcome predictor, as in the other workflows.

**Comment by sanadeem** [comment]
Might be worth trying out multiscale dynamical Ollivier Ricci curvature (https://arxiv.org/pdf/2106.05847.pdf), code here: https://zenodo.org/record/5031276#.Yj-bOBYpDYV.

Also topOMetry perhaps for diffusion pipeline: https://topometry.readthedocs.io/en/latest/index.html

**Comment by jimmymathews** [comment]
I would like to use the topometry package for a diffusion analysis. I'm thinking we should just replace the existing diffusion workflow (which works with 2D spatial cell arrangement as input) with topometry in multiplexed-channel space, as dimensional reduction and our go-to visualization for cell sets.
