### ISSUE TITLE
Explicit expression matrix

### ISSUE THREAD

**Issue by jimmymathews** [nadeemlab/SPT#76]
*For final state of criteria/features provided, see the rest of this comment thread.*

There are many usage scenarios where a model or statistic implementation requires a matrix representation of all "features".

Let's create a table, with a record for each cell, with fields:

1. Study identifier
2. Subject identifier
3. Specimen identifier
4. Outcome
5. Coordinate 1
6. Coordinate 2
7. <channel name> (one for each channel)

There are some limitations of this approach:
- Only one outcome.
- Intensity columns and discrete value columns not simultaneously present.

I think the benefit of simplicity outweighs these limitations for most scenarios. That is, e.g., removing the need for the model code to parse columns as outcome columns (there being just the one).

Create a workflow that writes an enormous TSV cells file with all of these fields. As a helper, include a simple JSON lookup of the identifiers pertaining to the first 3 fields (which should normally be occupied by integers): study names, subject names/identifiers, specimen names/identifiers. In case of anonymization only the study names will be non-trivial.

**Comment by jimmymathews** [comment]
This might result in an unmanageable dataframe / file if done as stated.
Let's use multiple dataframes in a nested dictionary, so that columns 1,2,3 are not needlessly repetitious.

**Comment by jimmymathews** [comment]
Probably this can use `spt countsserver cache-expressions-data-array`, as long as we're willing to use a file-mediated method. The file are a very efficient representation.

**Comment by jimmymathews** [comment]
This is being worked on in branch `issue76`. The plan is:

1. Normalize the db access even more. Every use of DatabaseConnectionMaker has some variant of the enter/exit pattern manually implemented; this will be factored into DatabaseConnectionMaker. This is not strictly part of this issue but it is helpful for it, so I'm taking the opportunity.
2. Factor countsserver::CompressedMatrixPuller into the portion that pulls a sparse representation into Python execution environment, and a portion that writes the binary format. The former portion will become a general-use function under workflow::common.
3. Add the expression matrix functionality by doing the sparse representation pull plus some dataframe stuff. Make sure this is available as dataframe, dictionary, or file write. The file write should probably be normally used via a new exposed CLI command, which doubles as a documentation vehicle for the new functionality as a whole.
4. Add a strict test of the expression pulling, testing that the resulting dataframe is exactly as expected. Possibly add a few finer-grained tests (for the future, in case of deliberate changes, to test the deliberate changes).

**Comment by jimmymathews** [comment]
(1) above is done.

**Comment by jimmymathews** [comment]
(2) above is done, as of c2bffcdc6198c7445ce8d1f247fd32f60d76aa30 . There is a new class SparseMatrixPuller, and a documented data-wrapper object CompressedDataArrays. There is also a new class CompressedMatrixWriter that just uses the CompressedDataArrays object.

**Comment by jimmymathews** [comment]
(3) and (4) are basically done, except the final aggregation will be awkward (does not work when multiple datasets present) until the planned improvements to the database schema providing project-level metadata.

**Comment by CarlinLiao** [comment]
Keeping an eye on this as it should provide an easier way to make SQL requests for `cg-gnn` up to date instead of the simple way I have implemented it currently in [cg-gnn#1](https://github.com/CarlinLiao/cg-gnn/pull/1)

**Comment by jimmymathews** [comment]
This was mostly implemented a long time ago, just needed to be updated to reflect the "sample strata" work.

Here is an example of how you use this:

```py
from spatialprofilingtoolbox.db.feature_matrix_extractor import FeatureMatrixExtractor
bundle = FeatureMatrixExtractor.extract('.spt_db.config')
```

The contents of `bundle` look like, for example:
```json
{
  "Melanoma intralesional IL2": {
    "feature matrices": {
      "lesion 0_1": {
        "dataframe":  pd.dataframe,
        "filename": "0.0.tsv"
      },
      "lesion 0_2": {
        "dataframe":  pd.dataframe,
        "filename": "0.1.tsv"
      },
      "lesion 0_3": {
        "dataframe":  pd.dataframe,
        "filename": "0.2.tsv"
      },
      "lesion 6_1": {
        "dataframe":  pd.dataframe,
        "filename": "0.3.tsv"
      },
      "lesion 6_2": {
        "dataframe":  pd.dataframe,
        "filename": "0.4.tsv"
      },
      "lesion 6_3": {
        "dataframe":  pd.dataframe,
        "filename": "0.5.tsv"
      },
      "lesion 6_4": {
        "dataframe":  pd.dataframe,
        "filename": "0.6.tsv"
      }
    },
    "channel symbols by column name": {
      "F0": "B2M",
      "F1": "B7H3",
      "F2": "CD68",
      "F3": "CD8",
      "F4": "DAPI",
      "F5": "FOXP3",
      "F6": "IDO1",
      "F7": "KI67",
      "F8": "LAG3",
      "F9": "MHCI",
      "F10": "MHCII",
      "F11": "MRC1",
      "F12": "CD14",
      "F13": "PD1",
      "F14": "PDL1",
      "F15": "S100B",
      "F16": "SOX10",
      "F17": "TGM2",
      "F18": "TIM3",
      "F19": "CD163",
      "F20": "CD20",
      "F21": "CD25",
      "F22": "CD27",
      "F23": "CD3",
      "F24": "CD4",
      "F25": "CD56"
    },
    "sample cohorts": {
      "assignments": pd.DataFrame,
      "strata": pd.DataFrame
    }
  }
}
```
where the dataframes (just denoted `pd.DataFrame` above) look like:

`bundle['Melanoma intralesional IL2']['feature matrices']['lesion 0_1']['dataframe']`:

| pixel x | pixel y | F0 | F1 | F2 | F3 | F4 | F5 | F6 | F7 | F8 | F9 | F10 | F11 | F12 | F13 | F14 | F15 | F16 | F17 | F18 | F19 | F20 | F21 | F22 | F23 | F24 | F25 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 5041.0 | 944.0 | 1 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 1 |
| 5106.0 | 952.0 | 1 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 1 |
| 4927.0 | 1001.0 | 1 | 1 | 0 | 0 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 1 |
| 4914.0 | 1315.0 | 1 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 1 | 1 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 1 | 1 | 0 |
| 4947.0 | 1314.0 | 1 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| 5289.0 | 1318.0 | 1 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 1 | 1 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 1 | 0 | 0 | 0 | 0 | 0 |
| ... |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |

...

`bundle['Melanoma intralesional IL2']['sample cohorts']['assignments']`:

|specimen | stratum identifier |
| --- | --- |
| lesion 0_1 | 1 |
| lesion 0_2 | 2 |
| lesion 0_3 | 2 |
| lesion 6_1 | 3 |
| lesion 6_2 | 4 |
| lesion 6_3 | 4 |
| lesion 6_4 | 3 |

`bundle['Melanoma intralesional IL2']['sample cohorts']['strata']`:

| stratum identifier | local temporal position indicator | subject diagnosed condition | subject diagnosed result |
| --- | --- | --- | --- |
| 1 | Before intervention | Response to intralesional IL-2 injection | Non-responder |
| 2 | After intervention | Response to intralesional IL-2 injection | Non-responder |
| 3 | Before intervention | Response to intralesional IL-2 injection | Extreme responder |
| 4 | After intervention | Response to intralesional IL-2 injection | Extreme responder |

**Comment by jimmymathews** [comment]
For future reference: This worked on a real/large dataset with N=2.5m cells and M=26 channels, taking about 10 minutes (roughly 5 minutes download and 5 minutes processing). The time of the operation is more or less bilinear in N and M.

I think some steps may have a large memory requirement, however. On a relatively low-powered server with I think 8GB of RAM the process crashed.

**Comment by CarlinLiao** [comment]
Is the proposal to replace querying the scstudies server via postgres with this function, importing the spt package and then calling this function to get the information and coercing it into cell graph format?

**Comment by jimmymathews** [comment]
Hm not necessarily. I was thinking that `spatialprofilingtoolbox.cggnn` would call this function and pass along its results to `cg-gnn` functions, in whatever format makes sense for `cg-gnn` functions. This would avoid the need for dependency of `cg-gnn` on `spatialprofilingtoolbox` (which would be circular).
