### ISSUE TITLE
Data model update

### ISSUE THREAD

**Issue by jimmymathews** [nadeemlab/SPT#94]
An update to the data model used by SPT is coming, and it includes project-level data as well as a more accurate representation of treatments/interventions and typical censorable survival data.

For this issue:
1. Add new tables or fields to the test datasets exemplifying the new data elements.
2. Update the import workflows to be compliant with the changes.
3. Update the views and materialized views to be compliant with the changes. This may be difficult, since most of these views have to do with "outcomes", which are now made more complicated. Possibly this can no longer be done with pure SQL, and will need a script to run that pre-fills some additional tables based on branching logic that assesses which "outcome-like" covariates are available.
4. Update the API handlers to be compliant with the changes (this is probably mostly the treatment/intervention stuff).
5. Add convenience API endpoints which accept larger study parameters, and look up component studies internally when necessary.
6. Add a few API endpoints serving up a few basic snippets of the project data (e.g. a contact, url , publication title if available).

Next steps after this issue is resolved include:
- Do (1) for the exemplar public data sets.
- Refresh the database schema and data with new imports.
- Release the new API server image to the demo application.

**Comment by jimmymathews** [comment]
(1) is done.

**Comment by jimmymathews** [comment]
The portion of (2) involving project data is done. Mainly involves new file [study.py](https://github.com/nadeemlab/SPT/blob/issue94/spatialprofilingtoolbox/workflow/source_file_adi_parsing/study.py).

**Comment by jimmymathews** [comment]
The portion of (1) involving treatement/intervention is done.

**Comment by jimmymathews** [comment]
(1) and (2) are now done (including the diagnosis/treatment/invertention updates).

**Comment by CarlinLiao** [comment]
I've created scripts in `/nadeem_lab/staging_preprocessing/` to convert the breast cancer and melanoma datasets from the old data model to the data model as of the time of this post. Let me know if you make further changes so I can update those scripts.

**Comment by jimmymathews** [comment]
Note that this issue needs to replace the views' references to the `histology_assessment_process` `assay` and `result`, which were used to stratify samples. In all the examples these sample-level "diagnoses" (though interesting for sample-level analysis) are not as important as sample stratifications derived from true subject-level diagnoses. For example, "*pre-treatment samples from patients who later responded (or didn't)*".

To support this replacement, I put in place a system that will automatically assign at most 1 "stratum" or class to a given sample as follows.

The extraction date places the sample in an inferred chronology of interventions, leading to an "interventional" component, a label indicating this temporal position. This can be blank if there are no interventions.

The extraction date also determines a most-consecutive diagnosis, of the subject from which the sample was extracted, in which the sample could have participated as evidence. This leads to a "diagnostic state" component, a label indicating this diagnosis.

The concatenation of these two components provides the label for the stratum.

This system doesn't cover every possibility. Notably it misses:
- The previously-handled case of truly sample-level assessments, e.g. grades assessed sample-by-sample.
- Samples grouped by non most-consecutive diagnoses, i.e. diagnoses pertaining to much later evidence as well.

For now I believe these omissions are acceptable, with several workarounds possible if needed.

The above is implemented with a new table, `sample_strata`, whose records are assignments of samples (specimens) to strata. Here is an example:

```txt
 identifier |        sample         | temporal_position_relative_to_interventions |                     subject_diagnosis                      
------------+-----------------------+---------------------------------------------+------------------------------------------------------------
          1 | lesion 0_1            | Before Intralesional IL-2 injection         | Response to intralesional IL-2 injection Non-responder
          1 | lesion 0_1            | Before Intralesional IL-2 injection         | Response to intralesional IL-2 injection Non-responder
          3 | lesion 6_4            | Before Intralesional IL-2 injection         | Response to intralesional IL-2 injection Extreme responder
          3 | lesion 6_4            | Before Intralesional IL-2 injection         | Response to intralesional IL-2 injection Extreme responder
          3 | lesion 6_1            | Before Intralesional IL-2 injection         | Response to intralesional IL-2 injection Extreme responder
          3 | lesion 6_1            | Before Intralesional IL-2 injection         | Response to intralesional IL-2 injection Extreme responder
          2 | lesion 0_2            | After Intralesional IL-2 injection          | Response to intralesional IL-2 injection Non-responder
          2 | lesion 0_3            | After Intralesional IL-2 injection          | Response to intralesional IL-2 injection Non-responder
          2 | lesion 0_3            | After Intralesional IL-2 injection          | Response to intralesional IL-2 injection Non-responder
          2 | lesion 0_2            | After Intralesional IL-2 injection          | Response to intralesional IL-2 injection Non-responder
          4 | lesion 6_2            | After Intralesional IL-2 injection          | Response to intralesional IL-2 injection Extreme responder
          4 | lesion 6_2            | After Intralesional IL-2 injection          | Response to intralesional IL-2 injection Extreme responder
          4 | lesion 6_3            | After Intralesional IL-2 injection          | Response to intralesional IL-2 injection Extreme responder
          4 | lesion 6_3            | After Intralesional IL-2 injection          | Response to intralesional IL-2 injection Extreme responder
          5 | BaselTMA_SP43_3_X13Y6 | Before Hormone therapy                      | Response to hormone therapy Refractory
          5 | BaselTMA_SP43_1_X1Y8  | Before Hormone therapy                      | Response to hormone therapy Refractory
          6 | BaselTMA_SP42_5_X8Y7  | Before Hormone therapy                      | Response to hormone therapy Sensitive
          6 | BaselTMA_SP43_4_X15Y3 | Before Hormone therapy                      | Response to hormone therapy Sensitive
```
I believe this finally captures, in an automated way, the logic of the study design of the exemplar datasets.

**Comment by jimmymathews** [comment]
Note that I am not adding this new table to the "data model", because it is entirely derivative and so, strictly speaking, its records do not add new data (facts). Moreover it is clearly designed for a specific purpose (sample stratification), making it inappropriate for the generally purpose-agnostic, factually-oriented data model.

**Comment by jimmymathews** [comment]
Just like the views.

**Comment by jimmymathews** [comment]
I believe (3) is done. And it does not alter the interface between the database and the API server, so I don't think (4) is actually necessary, although there might be a few names worth updating.

**Comment by CarlinLiao** [comment]
So there's no changes that need to be made to the extraction CSVs and TSVs, only the queries?

Two questions
1. What happens if there are multiple interventions to the same cohort with the same name, e.g., the treatment is two IL-2 injections at different times? Like COVID boosters.
2. What is the purpose of the subject_diagnosis field and why does it mash together the assay and result together?

**Comment by jimmymathews** [comment]
I think the only change to those TSVs is to provide "timepoint" indicators of chronology.
1. Yes, this case is not adequately handled... The obvious fix -- including the date in the interventional position label -- isn't necessarily desirable, because in the larger class of cases I think this will appear too verbose.
2. The purpose of the subject diagnosis field (and the intervention position field) is just to provide a label describing the stratum that the record is about. In the example, `0_1`, `6_1`, `6_4` are all pre-treatment samples, but `6_1` and `6_4` are from a patient who later responded and `0_1` is not. This is a meaningful distinction of cohorts. The downstream tools aim to make it possible to discover predictive markers, by looking at the difference of the attributes of the samples (the pathology data) between such meaningful cohorts. So the point is just to define the meaningful cohorts, and textually tag them in a way that suggests their meaning. That's why I was happy to concatenate the "assay" and "result" into a summary label; the contents are destined for the presentation layer. But this isn't really necessary.

**Comment by jimmymathews** [comment]
There is a case for factoring this stuff into a finer-grained table for analytics purposes followed by a derived presentation layer version (that mashes things together to form labels, etc.). Future work? Not sure if it is a high priority.

**Comment by jimmymathews** [comment]
Just a note for other future work: It would be very useful to augment the fractions/counts functionality (countsserver) with these covariates in addition to true cell-level attributes. So that any query about cells of a given phenotype can be easily restricted to these cohorts by repurposing the same implementation with new channels ("quasi" channels representing cohort assignment). Currently there is no way to do this in our UI.

**Comment by jimmymathews** [comment]
Maybe you're right, that it should be the responsibility of the API-using application to mash together field values if desired. It's not like it's that hard to do.
I just don't like having too many fields in cases where they aren't formally documented.
The mixed-lettercase caused by the concatenation is bothering me...

**Comment by jimmymathews** [comment]
The above payload now also includes a list of lists form of the sample_strata table.

**Comment by CarlinLiao** [comment]
Do you have an updated example of the sample_strata table?

**Comment by jimmymathews** [comment]
Sure. 

```
 stratum_identifier |        sample         | local_temporal_position_indicator |    reference_intervention    | reference_intevention_date |       subject_diagnosed_condition        | subject_diagnosed_result | subject_diagnosed_date 
--------------------+-----------------------+-----------------------------------+------------------------------+----------------------------+------------------------------------------+--------------------------+------------------------
 1                  | lesion 6_1            | Before                            | Intralesional IL-2 injection | timepoint 2                | Response to intralesional IL-2 injection | Extreme responder        | timepoint 3
 2                  | lesion 6_3            | After                             | Intralesional IL-2 injection | timepoint 2                | Response to intralesional IL-2 injection | Extreme responder        | timepoint 3
 2                  | lesion 6_2            | After                             | Intralesional IL-2 injection | timepoint 2                | Response to intralesional IL-2 injection | Extreme responder        | timepoint 3
 1                  | lesion 6_4            | Before                            | Intralesional IL-2 injection | timepoint 2                | Response to intralesional IL-2 injection | Extreme responder        | timepoint 3
 3                  | lesion 0_3            | After                             | Intralesional IL-2 injection | timepoint 2                | Response to intralesional IL-2 injection | Non-responder            | timepoint 3
 4                  | lesion 0_1            | Before                            | Intralesional IL-2 injection | timepoint 2                | Response to intralesional IL-2 injection | Non-responder            | timepoint 3
 3                  | lesion 0_2            | After                             | Intralesional IL-2 injection | timepoint 2                | Response to intralesional IL-2 injection | Non-responder            | timepoint 3
 1                  | BaselTMA_SP43_4_X15Y3 | Before                            | Hormone therapy              | timepoint 2                | Response to hormone therapy              | Sensitive                | timepoint 2
 2                  | BaselTMA_SP43_1_X1Y8  | Before                            | Hormone therapy              | timepoint 2                | Response to hormone therapy              | Refractory               | timepoint 2
 1                  | BaselTMA_SP42_5_X8Y7  | Before                            | Hormone therapy              | timepoint 2                | Response to hormone therapy              | Sensitive                | timepoint 2
 2                  | BaselTMA_SP43_3_X13Y6 | Before                            | Hormone therapy              | timepoint 2                | Response to hormone therapy              | Refractory               | timepoint 2
```

This can be obtained from the Docker image `nadeemlab/spt-db-preloaded-1and2` that is built during testing.
I run a container from the image (e.g. `docker compose up` in `countsserver`) and query it using `psql`. The way I actually do the latter is by spinning up a second container, based on image `nadeemlab-development/spt-development`, since it has `psql` pre-installed and because the containers can easily talk to each other on the same network Docker sets up.

**Comment by CarlinLiao** [comment]
Ok I'm generally satisfied with the utility and comprehensiveness of the sample_strata table, with the exception of the identifier column, which I'm a little iffy on. It's not immediately obvious what it's for and doesn't hold any meaning by itself. In order to use it you'd have to grab a number and then figure out what stratum it identifies, or figure out what detail grouping you want, then figure out which stratum value that matches, then grab the rows with the same identifier. In that case, wouldn't you just use several WHERE clauses on the table instead?

**Comment by jimmymathews** [comment]
See the usage of this identifier here in [create_views.sql](https://github.com/nadeemlab/SPT/blob/e2c1eeae62731d64f26e99b8390c9640730457b0/spatialprofilingtoolbox/db/data_model/create_views.sql#L173) (and in dozens of additional places in that file).
It's used as a case indicator. Without it create_views.sql would have to carry forward all 6 columns in dozens of places.

**Comment by jimmymathews** [comment]
I'm planning to expose this as "sample cohort 1" "sample cohort 2" or similar in the frontend as well. Because it will show the user a large table of stats by case, one facet of which is the sample cohort/stratum, and I think it would be far too verbose to repeat all the attributes of the stratum for every one of ~1000 rows in a web page.
