### ISSUE TITLE
Repository management frameworks refactor

### ISSUE THREAD

**Issue by jimmymathews** [nadeemlab/SPT#95]
The current setup uses GNU `make` to fulfill the following functions:

1. Create Dockerfiles specifying Docker images specific to each "module" in this repository (plus a few images for testing only).
2. Build Docker images for each "module". Some images for "production" and some for testing only. Includes retrieving/installing dependencies.
3. Setup and teardown testing environments comprised of Docker compositions.
4. Run tests in a container.
5. Build the Python package.
6. Release (push) the Python package to PyPI.
7. Release (push) the Docker images to Docker Hub.
8. Provide a common command-line entry point to all of the above.

Previously, all of the above except (8) were performed with ad-hoc `bash` scripts.

I chose `make` not because of personal familiarity with it (as you can see from the low quality of the Makefiles!), but rather because:

a. It is widely available, being part of the POSIX specification.
b. It has few external dependencies.
c. Its end-user call syntax is well-known.
d. Its primary purpose is to coordinate and track dependent actions.
e. It flexibly accomodates arbitrary (local) actions.

However, few developers know how to write Makefiles anymore. This creates a big maintenance risk.

Also, the functions (1)-(7) above are probably very well-fulfilled by contemporary frameworks:

- (1), (2), (3), (7) by some container-management framework
- (4), (5) by a testing framework and IDE
- (6), (7) by a CICD framework

Frameworks generally offer the promise of solving common problems in a systematic and reproducible way. Yet it is difficult work to select an appropriate mix of frameworks while avoiding vendor hype, unneeded runtime dependency bloat, unneeded cloud services, unnecessary new steps to learn and explain, etc.

For this issue:

- Research the pertinent frameworks.
- Recommend an appropriate mix.
- Implement it.

(Reminder: Let us work in a branch named after the issue, like `issue##`.)

**Comment by CarlinLiao** [comment]
A lot of what we talked about in #84 and #86 overlap with the requests here.

**Comment by jimmymathews** [comment]
Weirdly there seems to be no clear alternative to `make`.

Also the sort-of elaborate test harness based on docker compose and lots of docker images is pretty effective at providing alignment between the expected production environment and the test environment.

I'm going to close this because it doesn't seem very high priority. Perfectly happy to re-open if anyone can suggest and make the case for alternatives.
